# Docker Compose file for a PHP web server with Apache and a MariaDB database
services:
  web:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: webserver
    restart: always
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"



  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rakoczi2012
      MYSQL_DATABASE: 3cxplusz
      MYSQL_USER: 3cxuser
      MYSQL_PASSWORD: Rakoczi2012
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: 3cxuser
      PMA_PASSWORD: Rakoczi2012
    restart: always
    ports:
      - "8081:80"

volumes:
  db_data:
